// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu3VCQIUW_bf908KA7717pa2k_8f7XW6E',
    appId: '1:678916309599:android:31a56e768d17d68457d1ea',
    messagingSenderId: '678916309599',
    projectId: 'safe-her-project-258df',
    storageBucket: 'safe-her-project-258df.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjnTAyu0PcqnRoVF2rQupLGapRCuZcCiw',
    appId: '1:678916309599:ios:c8299cef80216d7457d1ea',
    messagingSenderId: '678916309599',
    projectId: 'safe-her-project-258df',
    storageBucket: 'safe-her-project-258df.firebasestorage.app',
    iosBundleId: 'com.example.safeHer',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_J8q65RVlHdENPXCPftGOuOIupd2OOpQ',
    appId: '1:678916309599:web:a54fdf455a1603e057d1ea',
    messagingSenderId: '678916309599',
    projectId: 'safe-her-project-258df',
    authDomain: 'safe-her-project-258df.firebaseapp.com',
    storageBucket: 'safe-her-project-258df.firebasestorage.app',
    measurementId: 'G-CBNY3W5KEX',
  );
}
