// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6NY_wyyLWeTIB5T7tX3G6cdPfdGaHvZ0',
    appId: '1:787237729831:android:8ec820af49bc1e82694002',
    messagingSenderId: '787237729831',
    projectId: 'safeher-9ca47',
    storageBucket: 'safeher-9ca47.firebasestorage.app',
  );

  // NOTE: still pointing at the old "safeher-206b6" project — no iOS app
  // has been registered on the new "safeher-9ca47" project yet. Register
  // one in Firebase Console (or via `flutterfire configure`) before
  // building for iOS, otherwise it'll hit the old, unrelated project.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvuYfpmzuD94UfKi5E7yKvf39ruXt68lw',
    appId: '1:831160190675:ios:9832a3e44d7bab1221b626',
    messagingSenderId: '831160190675',
    projectId: 'safeher-206b6',
    storageBucket: 'safeher-206b6.firebasestorage.app',
    iosBundleId: 'com.example.safeHer',
  );
}
